Repository expressots/expressots-cli, pull requests merged in 2024-08, with the labels that each got.

#55 Fix/remove nodejs version limitation
  package.json
  src/new/cli.ts
  src/new/form.ts
  src/utils/cli-ui.ts
Labels: bug, enhancement

#57 fix: update usecase to UseCase nonop template
  expressots.config.ts
  src/generate/utils/nonopininated-cmd.ts
Labels: enhancement

#59 Fix/adjust provider
  package.json
  src/cli.ts
  src/commands/project.commands.ts
  src/generate/cli.ts
  src/help/cli.ts
  src/help/form.ts
  src/info/cli.ts
  src/new/cli.ts
  src/new/form.ts
  src/providers/add/cli.ts
  src/providers/add/form.ts
  src/providers/cli.ts
  src/providers/create/cli.ts
  src/providers/create/form.ts
  src/providers/index.ts
  src/utils/change-package-info.ts
  src/utils/cli-ui.ts
Labels: enhancement

#60 Feature/detect template break changes
  package.json
  src/cli.ts
  src/commands/project.commands.ts
  src/info/form.ts
  src/providers/prisma/prisma.provider.ts
  src/providers/prisma/templates/base-repository.interface.tpl
  src/providers/prisma/templates/base-repository.tpl
Labels: bug, enhancement

#61 fix: broken tsconfig deps
  src/commands/project.commands.ts
  src/help/form.ts
Labels: bug

#63 feat: add the script command
  src/cli.ts
  src/help/form.ts
  src/scripts/cli.ts
  src/scripts/form.ts
  src/scripts/index.ts
Labels: enhancement

#64 [Snyk] Upgrade semver from 7.6.2 to 7.6.3
  package.json
Labels: lib update
